### ISSUE TITLE
Update Axios version

### ISSUE THREAD

**Issue by didoda** [atlasconsulting/bedita-sdk-js#27]
We should update axios version from 0.25.6 to latest.

```
axios                             latest  0.25.0   ❯  1.2.6     https://axios-http.com
```

**Comment by batopa** [comment]
Since the major version 1 of axios could lead to issue in apps using the sdk,  the [upgrade](https://github.com/atlasconsulting/bedita-sdk-js/commit/a650a4c3408c18e22fe05e1f3a203d9bae555ddc) has been done in `beta ` branch and it will released to v3.
